version: "3"
services:
  nginx-app-dev:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - "/home/dev_nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/home/linweifan.xyz_bundle.crt:/etc/nginx/ssl/linweifan.xyz_bundle.crt"
      - "/home/linweifan.xyz.key:/etc/nginx/ssl/linweifan.xyz.key"
